// `worker-configuration.d.ts` (auto-generated by `wrangler types`) declares
// every binding and every secret currently set in `.dev.vars` or via
// `wrangler secret put`. Re-run `wrangler types` whenever those change.
//
// This file augments that with secrets that may be UNSET at runtime — wrangler
// can't infer them, but the code path still references them. Interface
// merging on `Cloudflare.Env` is the Cloudflare-recommended pattern for this.

export {} // marks this file as a module so `declare global` works

declare global {
  namespace Cloudflare {
    interface Env {
      // Comma-separated origin allowlist. Used by both:
      //   - the WS-upgrade Origin check (apps/game-server/src/origin.ts)
      //   - Better Auth's trustedOrigins (apps/game-server/src/auth.ts)
      // Unset in dev → permissive localhost + RFC 1918 matching.
      // Set in production (`wrangler secret put ALLOWED_ORIGINS`).
      ALLOWED_ORIGINS?: string
      // Sentry DSN for the Worker (SKILL.md § 5). Optional — when unset
      // (typical local dev) the Sentry SDK initializes in a disabled state
      // and every capture call no-ops.
      SENTRY_DSN_WORKER?: string
    }
  }
}
